Repository lamoda/gonkey, pull requests merged in 2021-09, with the labels that each got.

#96 mocks file reply strategy: show error when no file found by filepath
  mocks/loader.go
  mocks/reply_strategy.go
Labels: bug, patch

#95 new: added missing $matchRegexp to examples
  README-ru.md
  README.md
Labels: documentation, skip-release

#94 new: support variables in mock definition
  README-ru.md
  README.md
  testloader/yaml_file/test_variables_test.go
  testloader/yaml_file/testdata/variables.yaml
  variables/variables.go
Labels: enhancement, skip-release

#99 doc: update Readme files - backslash in regexp should be escaped
  README-ru.md
  README.md
Labels: documentation, skip-release
