Repository lamoda/gonkey, pull requests merged in 2021-12, with the labels that each got.

#109 Use fixtures.Postgres as default DbType when run tests
  .github/workflows/ci-build.yml
  README-ru.md
  README.md
  fixtures/loader.go
  go.mod
  go.sum
  runner/runner_testing.go
Labels: minor, internal

#112 [BUG] fixed DbType param in console client
  main.go
Labels: bug, minor

#110 added bodyMatchesText requestConstraint with example test
  README-ru.md
  README.md
  examples/mock-body-matching/cases/do.yaml
  examples/mock-body-matching/func_test.go
  examples/mock-body-matching/main.go
  mocks/loader.go
  mocks/request_constraint.go
Labels: documentation, enhancement, minor

#113 Write paths to test files in test output
  models/test.go
  output/console_colored/console_colored.go
  output/testing/testing.go
  testloader/yaml_file/parser.go
  testloader/yaml_file/test.go
  testloader/yaml_file/test_definition.go
  testloader/yaml_file/test_test.go
Labels: enhancement, patch

#114 Allow passing variables to dbQuery and dbResponse
  README-ru.md
  README.md
  examples/with-db-example/Makefile
  examples/with-db-example/cases/database-with-vars.yaml
  examples/with-db-example/docker-compose.yaml
  examples/with-db-example/server.dockerfile
  examples/with-db-example/server.py
  models/test.go
  runner/runner.go
  runner/runner_upload_file_test.go
  testloader/yaml_file/test.go
  variables/variables.go
Labels: enhancement, minor

#115 Add `skipped`, `broken` and `focus` statuses for tests definitions & export statuses in allure report's
  README-ru.md
  README.md
  examples/with-db-example/cases/focused-tests.yaml
  examples/with-db-example/cases/skipped-and-broken-tests.yaml
  models/result.go
  models/test.go
  output/allure_report/allure_report.go
  output/console_colored/console_colored.go
  runner/runner.go
  testloader/yaml_file/test.go
  testloader/yaml_file/test_definition.go
Labels: enhancement, minor

#116 fix: error in documentation
  README-ru.md
  README.md
Labels: documentation, patch
