Repository lamoda/gonkey, pull requests merged in 2021-03, with the labels that each got.

#81 Automate release
  .autorc
  .github/workflows/autorelease.yml
Labels: skip-release

#79 Фикс проверки для #78
  compare/compare.go
  compare/compare_test.go
Labels: patch

#82 fix: remove dependency from go-openapi
  checker/addons/openapi2_compliance/checker.go
  checker/addons/openapi2_compliance/go.mod
  checker/addons/openapi2_compliance/go.sum
  go.mod
  go.sum
  main.go
Labels: enhancement, minor
