Repository lamoda/gonkey, pull requests merged in 2022-05, with the labels that each got.

#117 new: add comparisonParams to BodyMatches for Json and XML
  compare/compare.go
  mocks/loader.go
  mocks/request_constraint.go
  testloader/yaml_file/test_definition.go
Labels: enhancement

#155 #133 | fix data race
  mocks/service_mock.go
Labels: bug, skip-release, internal

#132 New: regexp in query matching
  README-ru.md
  README.md
  compare/compare_query.go
  compare/compare_query_test.go
  mocks/loader.go
  mocks/request_constraint.go
  mocks/request_constraint_test.go
Labels: enhancement, minor

#154 New: ignore db ordering in dbResponse feature
  README-ru.md
  README.md
  checker/response_db/response_db.go
  checker/response_db/response_db_test.go
  compare/compare.go
  models/test.go
  testloader/yaml_file/test.go
Labels: enhancement, minor
