Repository lamoda/gonkey, pull requests merged in 2022-06, with the labels that each got.

#159 feat: add ? to query
  README-ru.md
  README.md
  testloader/yaml_file/test.go
  testloader/yaml_file/test_variables_test.go
Labels: enhancement, patch

#160 Added table of contents. Also fixed some markdownlint issues in README.
  README-ru.md
  README.md
Labels: documentation

#162 Add `template` mock strategy for use incoming request inside mock responses
  README-ru.md
  README.md
  examples/mock-based-on-request/cases/do.yaml
  examples/mock-based-on-request/main.go
  go.mod
  go.sum
  mocks/loader.go
  mocks/template_reply_strategy.go
Labels: enhancement, minor

#166 Use regexp matching inside database response checks
  README-ru.md
  README.md
  checker/response_db/response_db.go
  checker/response_db/response_db_test.go
  examples/with-db-example/cases/database-with-vars.yaml
Labels: enhancement, patch
