Repository lamoda/gonkey, pull requests merged in 2022-08, with the labels that each got.

#171 Added JSON-Schema and how to set it up in readme
  README-ru.md
  README.md
  gonkey.json
Labels: documentation, skip-release

#172 With-db-example .PHONY fix.
  examples/with-db-example/Makefile
Labels: skip-release

#179 Fix finalizing allure reports.
  runner/runner_testing.go
Labels: bug, patch
