Repository lamoda/gonkey, pull requests merged in 2023-01, with the labels that each got.

#180 feature: cases variables through tests
  README-ru.md
  README.md
  examples/with-cases-example/cases/do.yaml
  examples/with-cases-example/func_test.go
  examples/with-cases-example/main.go
  models/test.go
  runner/runner.go
  testloader/yaml_file/parser.go
  testloader/yaml_file/parser_test.go
  testloader/yaml_file/test.go
  testloader/yaml_file/test_definition.go
  testloader/yaml_file/test_variables_test.go
  testloader/yaml_file/testdata/combined-variables.yaml
Labels: enhancement, skip-release

#151 issues-147: add description to tests
  README.md
  models/test.go
  output/allure_report/allure_report.go
  output/allure_report/beans/test.go
  output/console_colored/console_colored.go
  output/testing/testing.go
  testloader/yaml_file/parser.go
  testloader/yaml_file/test.go
  testloader/yaml_file/test_definition.go
Labels: enhancement, skip-release

#197 Update doc with "description" field
  README-ru.md
  gonkey.json
Labels: documentation, skip-release

#198 Load Postgres fixtures in a single transaction, truncate all tables at once
  fixtures/postgres/postgres.go
  fixtures/postgres/postgres_test.go
Labels: skip-release, internal

#195 new: introduce dropRequest strategy
  README-ru.md
  README.md
  gonkey.json
  mocks/loader.go
  mocks/reply_strategy.go
Labels: enhancement, minor
